sudo: required
services:
  - docker

before_install:
  - docker build -t bnprashanth/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true bnprashanth/react-test npm run test -- --coverage

after_success:
  - docker build -t bnprashanth/multi-client ./client
  - docker build -t bnprashanth/multi-nginx ./nginx
  - docker build -t bnprashanth/multi-server ./server
  - docker build -t bnprashanth/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push bnprashanth/multi-client
  - docker push bnprashanth/multi-nginx
  - docker push bnprashanth/multi-server
  - docker push bnprashanth/multi-worker